
# Manipulation de fichiers


# open

Le mode est donné sous la forme d'une chaîne de caractères. Voici les principaux modes :

    'r' : ouverture en lecture (Read).

    'w' : ouverture en écriture (Write). Le contenu du fichier est écrasé. Si le fichier n'existe pas, il est créé.

    'a' : ouverture en écriture en mode ajout (Append). On écrit à la fin du fichier sans écraser l'ancien contenu du fichier. Si le fichier n'existe pas, il est créé.
    

In [1]:
f = open("toto.txt",mode='w')
f.write('yep')

3

# close

Lorsque l'on a fini de manipuler un fichier ouvert, il est normalement necessaire de le fermer, pour liberer les ressources liées à ce fichier

In [2]:
f.close()

# with

La "vraie" maniere de faire consiste a utiliser le mot-clé "with". Ceci evite d'avoir à fermer explicitement le fichier avec close

In [3]:
with open("toto.txt",'r') as f:  # le fichier existe à l'avance sinon error
    print(f.closed) ## closed (et pas 'close') est un marqueur booleen indiquant si le fichier est ouvert ou fermé
print(f.closed)


False
True


# read

In [4]:
### je veux voir le contenu de mon fichier
with open("toto.txt",'r') as f:
    val = f.read() 
print('val : ', val)

val :  yep


tout le contenu du fichier est lu d'un coup

# readlines

In [5]:
# let write a multi line
txt = """yep
yop
yip
"""
with open("toto2.txt",'w') as f:
    f.write(txt)

In [6]:
### je veux voir le contenu de mon fichier ligne par ligne
f = open("toto2.txt",'r')
lines = f.readlines()
f.close()
print(lines)

['yep\n', 'yop\n', 'yip\n']


# Lecture string/bytes et importance de l'encoding (UTF-8)


In [12]:
chaine1 = b"Ceci est une chaine d'octets"

print(chaine1)
print(type(chaine1))
print(chaine1[-1])

chaine2 = "Ceci est une chaine de caractères particuliers 你好 صباح الخير"

print(chaine2)
print(type(chaine2))
print(chaine2[-2])


b"Ceci est une chaine d'octets"
<class 'bytes'>
115
Ceci est une chaine de caractères particuliers 你好 صباح الخير
<class 'str'>
ي


In [13]:
# lets put this 2 object in the same file
with open("chaine.txt",'wb') as f:
    f.write(chaine1)

with open("chaine.txt",'a') as f:
    f.write('\n')
    f.write(chaine2)

In [14]:
with open('chaine.txt', mode= 'r', encoding='utf8') as f:
    txt = f.read()
print(txt, type(txt), len(txt))

Ceci est une chaine d'octets
Ceci est une chaine de caractères particuliers 你好 صباح الخير <class 'str'> 89


In [15]:
with open('chaine.txt', mode='rb') as f:
    b = f.read()
print(b, type(b), len(b))

b"Ceci est une chaine d'octets\nCeci est une chaine de caract\xc3\xa8res particuliers \xe4\xbd\xa0\xe5\xa5\xbd \xd8\xb5\xd8\xa8\xd8\xa7\xd8\xad \xd8\xa7\xd9\x84\xd8\xae\xd9\x8a\xd8\xb1" <class 'bytes'> 103


In [16]:
txt2 = b.decode('utf8')
print(txt2, type(txt2))

Ceci est une chaine d'octets
Ceci est une chaine de caractères particuliers 你好 صباح الخير <class 'str'>


# Sauvegarde et lecture avec numpy : format texte


## loadtxt 

In [18]:
import numpy as np

data = np.loadtxt('./data/Coords.txt') 
print (data)


[[-12.  56.   4.]
 [  6.  50.  12.]
 [  8.  36.   2.]
 [ 24.  24. -18.]
 [-12.  22.  28.]
 [-12.  22.  26.]
 [-32.  20. -18.]
 [-28.  16.  32.]
 [-48.  14.   8.]
 [-10.  10.  44.]
 [-34.   8.  38.]
 [  4.   6.  50.]
 [  4.   6.  50.]
 [ 10.   4.  74.]
 [ -2.   4.  44.]
 [ 24.   4. -10.]
 [ 24.   4. -16.]
 [ 40.   2.  62.]
 [-54.   2.  38.]
 [-26.  -4.  70.]]


## savetxt

In [19]:
data = np.zeros(shape = (1000,1000), dtype = "float32")
print(data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
np.savetxt("data.txt", data, fmt = "%f")

# Sauvegarde et lecture avec numpy : format .npy, load et save

In [23]:
np.save("data.npy", data)

In [24]:
data2 = np.load("data.npy")
data2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

# Concept d'Arborescence

![Image](./img/mac_tree.png)     ![Image](./img/win_tree.jpg)    ![Image](./img/linux-tree.png)

Racine :

    mac et linux : /
    
    windows : C:\
            


Chemin absolu :
    
    linux : /home/alex/projets/formation_python/
    
    windows : C:\\Users\\alex\\projets\\formation_python\\   (double\ car caractère d'échapement)
    
    mac : /Disque dur/Users/alex/projets/formation_python/

Chemin relatif :

    ./          là ou je suis actuellement
    ../       je remonte d'un dossier par rapport à là ou je suis
    
    idem windows mais avec \
    
    
    exemple : np.loadtxt('./data/Coords.txt') 
    
    

## Le module os (Operating System)



### 1 - Prendre de l'information sur le sysème de fichiers

+ import os


+ os.uname() : infos système


+ os.getcwd() : pour obtenir le répertoire en cours


+ os.path.abspath(path) : retourne une version absolue du chemin path


+ os.path.relpath(path[, start]) : retourne une version relative du chemin path. Par défaut, par rapport au working dir, sinon : spécifier un argument start qui sera le répertoire de base


### 2 - Faire des actions sur le système de fichiers

+ os.chdir(foldername)  : va dans le répertoire spécifié


+ os.mkdir(’mydir’) : crée le répertoire mydir


+ os.rename(oldname, newname) : renomme oldname en newname


+ os.remove(filename) : efface le fichier filename


### 3 - Utilitaires

+ os.path.join(morceau1, morceau2) : colle deux morceaux de chemin ensemble  en utilisant les caractères adaptés au système


+ os.path.expanduser("~") : retourne le chemin vers le répertoire "Home" de l'utilisateur sur la machine


+ os.path.split(racine/nomfichier_ou_rep) : permet de séparer la dernière branche de la racine, résultat sous forme de tuple
    *ex : (filepath, filename) = os.path.split("/Users/admin/Desktop") 
    *filename: "Desktop"


+ os.path.splitext(nomfichier.extension) : sépare le nom de l'extension. Résultat sous forme de tuple


+ os.listdir(path) :  prend un nom de chemin et retourne une liste du contenu du répertoire.


+ os.path.isfile : pour séparer les fichiers des répertoires. (os.path.isdir existe aussi). isfile prend un nom de chemin et :
     *retourne 1 / True si le chemin représente un fichier
     *0 / False dans le cas contraire. 


+ os.walk(top, topdown=True) : à parir de top (repertoire racine), parcourt l'arborescence en descendant si topdown=True, en montant sinon, et renvoie un tuple : (dirpath, dirnames, filenames) qui contient tous les répertoires dirnames rencontrés avec les fichiers filenames qui s'y trouvent

>for dossier, sous_dossiers, fichiers in os.walk('/tmp/test'):

>        for fichier in fichiers:

>            print(os.path.join(dossier, fichier))

In [25]:
import os
os.listdir('./')

['exercice_eeg.ipynb',
 'toto2.txt',
 'data.npy',
 'data.txt',
 'numpy_indexing.ipynb',
 'toto.txt',
 'loop_index_slice.ipynb',
 'img',
 'mafigure.svg',
 'chaine.txt',
 'data',
 'file_manipulation.ipynb',
 'numpy_base.ipynb',
 'matplotlib_base.ipynb',
 'Base_language.ipynb',
 'numpy_advanced.ipynb',
 'eeg_MNE.ipynb']

## Le module pathlib = nouvelle méthode

In [26]:
from pathlib import Path

home = Path.home()
home


PosixPath('/home/samuel')

In [27]:
ici = Path('.').absolute()
ici

PosixPath('/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks')

In [28]:
doc = home / 'Documents'
doc

PosixPath('/home/samuel/Documents')

In [29]:
for item in Path('/').iterdir():
    print(item)

/snap
/home
/lib64
/var
/proc
/dev
/boot
/etc
/lib
/root
/usr
/bin
/media
/lib32
/srv
/opt
/lost+found
/tmp
/libx32
/sbin
/mnt
/sys
/run


In [30]:
file_path = Path('/home/samuel/Figure_1.png')

print(file_path.is_file())

print(file_path.stem)
print(file_path.suffix)
print(file_path.parent)
print(file_path.parents[0])
print(file_path.parents[1])
print(file_path.parents[2])



False
Figure_1
.png
/home/samuel
/home/samuel
/home
/


In [31]:
ici = Path('.').absolute()

for file in ici.glob('*.ipynb'):
    print(file)

/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/exercice_eeg.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/numpy_indexing.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/loop_index_slice.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/file_manipulation.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/numpy_base.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/matplotlib_base.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/Base_language.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/numpy_advanced.ipynb
/home/samuel/Documents/Formation_2024_CorneyllieGarcia_Python_CalculScientifique/notebooks/eeg_MNE.ipynb


In [33]:
# recursif
for file in Path('/home/samuel/Documents').glob('**/*.ipynb'):
    print(file)


/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/exercice_eeg.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/exo_final.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/pandas_exo.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/numpy_indexing.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/loop_index_slice.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/xarray.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/pandas_base.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/seaborn.ipynb
/home/samuel/Documents/Formation_2023_GarciaCorneyllie_Python_CalculScientifique/notebooks/python-neo.ipynb
/home/samuel/Documents/

## exercice 1

Faire un script pour explorer le dossier 'data/data_folder'

Lire les datas dans une structure hierachique adaptée (dict/list/array)



## solution 1