
# Introduction Numpy


Numpy est une librairie d'extention à Python pour les tableaux multidimentionnels.
- calcul vectoriel avec représentation multidimentionnelle (ex : vecteur 1D, serie temporelle 2D, IRMAnat 3D, IRM Fonctionnelle 4D)
- efficace en gestion mémoire (proche hardware - gd ensemble de nbres ordonnés)
- conçu pour le calcul scientifique
- "brique" de base pour tout l'ecosystème scientifique (pandas/nipype/mne/scipy/...)

In [2]:
import numpy as np             # convention d'import
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

Opérations numériques rapides :

In [3]:
L = list(range(1000))             # Liste
%timeit [i**2 for i in L]

a = np.arange(1000)         # Numpy array
%timeit a**2

#pouquoi ? numpy est écrit en C !

143 µs ± 412 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
589 ns ± 2.92 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Doc : http://docs.scipy.org/

Aide interractive :

In [5]:
import numpy as np 
#np. + touche 'tab'
np.array?


Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [6]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

# Multi-dimensions : ndim, shape, size

## 1D

In [7]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [8]:
a.ndim

1

In [9]:
a.shape # 'taille' des dimensions

(4,)

In [10]:
a.size # nbre d'elements total

4

## 2D, 3D, ... ND

In [12]:
b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print('b : ', b)
print('b.ndim : ', b.ndim)
print('b.shape : ', b.shape)
print('b.size : ', b.size)

# attention à la necessité de dimentions cohérentes 
# b = np.array([[0, 1, 2], [3, 4, 5, 6]]) va pas marcher

b :  [[0 1 2]
 [3 4 5]]
b.ndim :  2
b.shape :  (2, 3)
b.size :  6


In [13]:
c = np.array([
        [[1,2,3], [2,3,4], [3,4,5], [4,5,6]],
        [[2,3,4], [3,4,5], [4,5,6], [5,6,7]],
        [[3,4,5], [4,5,6], [5,6,7], [6,7,8]],
        [[4,5,6], [5,6,7], [6,7,8], [7,8,9]],
        [[5,6,7], [6,7,8], [7,8,9], [8,9,10]]
    ])
print('c.ndim : ', c.ndim)
print('c.shape : ', c.shape)
print('c.size : ', c.size)

c.ndim :  3
c.shape :  (5, 4, 3)
c.size :  60


![Image](./img/np_3D.png)

# Fonctions

En pratique, on entre rarement les nombres à la main...

### Eléments réguliairement espacés :

In [15]:
a = np.arange(10) # 0 .. n-1  (!)
a
#np.arange?
#equivalent du range mais en numpy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(1, 9, 2) # début, fin (exclusive), pas
b

array([1, 3, 5, 7])

### Ou espacés en donnant le nombre de points :

In [18]:
c = np.linspace(0, 1, 6)   # début, fin, nombre de points
c
#np.linspace?
# attention, ici c'est inclus !

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
d = np.linspace(0, 1, 5, endpoint=False)
d

#(intro mot clef)

array([0. , 0.2, 0.4, 0.6, 0.8])

### Tableaux usuels :

In [15]:
a = np.ones((3, 3))  # np.ones((3, 3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
b = np.zeros((2, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
c = np.random.rand(10)      # distribution uniforme entre [0, 1]
c

array([0.46351601, 0.42609035, 0.69442761, 0.69757489, 0.59830286,
       0.41773387, 0.02481098, 0.97658285, 0.10723247, 0.72209852])

In [18]:
d = np.random.randn(4)      # distribution gaussian de moy 0 et stdv 1
d

array([-1.17169672,  0.98525295,  0.3076084 ,  1.48949845])

In [19]:
e = np.random.randint(0, 5, size=(2, 4))
e

array([[2, 2, 4, 4],
       [1, 0, 4, 3]])

# dtype

In [23]:
a = np.array([0, 1, 2, 3])
print(a)
a.dtype

[0 1 2 3]


dtype('int64')

In [24]:
b = np.array([0., 1., 2., 3.])
print(b)
b.dtype


[0. 1. 2. 3.]


dtype('float64')

In [25]:
import numpy as np
d = np.array([1.33,2,3.,4])
print(d)
d.dtype

# en numpy, les tableaux sont forcément homogènes car ils sont continus et compactes en mémoire.
# lors de mix numpy prends le dtype le plus utile 

[1.33 2.   3.   4.  ]


dtype('float64')

### Vous devez expliciter le dtype à la création

In [32]:
c1 = np.arange(10, dtype='float64')
print(c1)
c1.dtype
#import sys
#sys.getsizeof(c1) # taille en mémoire en byte (octet)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [31]:
c2 = np.arange(10, dtype='int16')
print(c2)
c2.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int16')


### Le type par défaut est généralement "float64" 

In [33]:
a = np.ones((3, 3))
print(a)
print(a.dtype)

b = np.ones((3, 3), dtype = "int32")
print(b)
b.dtype

# d'ou, la bonne pratique est de spécifier le dtype à chaque fois

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int32')

### Autres types :

In [34]:
# Complexe :
a = np.array([1+2j, 3+4j, 5+6*1j])
a.dtype

dtype('complex128')

In [35]:
# Booléen
b = np.array([True, False, False, True])
b.dtype

dtype('bool')

In [20]:
# String
c = np.array(['Bonjour', 'Hello', 'Hallo',])
c.dtype             # <--- strings contenant max. 7 lettres

# U7 : unique 7 caractere

dtype('<U7')

# Introduction aux opérations

In [37]:
c = np.arange(10, dtype='float64')
d = np.arange(10, dtype='float64')

print('c : ', c)
print('d : ', d)

c :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
d :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
c+1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
c+d

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [41]:
c*10+d

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [42]:
res = np.log10(c)
print(res)

[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


/tmp/ipykernel_5373/2825777501.py:1: RuntimeWarning: divide by zero encountered in log10
  res = np.log10(c)


In [43]:
flags = np.isinf(res)
flags

array([ True, False, False, False, False, False, False, False, False,
       False])

In [44]:
np.inf

inf

In [45]:
-np.inf

-inf

In [46]:
np.nan #Not A Number

nan

In [47]:
np.nan + 5

nan

In [31]:
a = np.arange(9)
print(a)
flags = (a>5)
flags

[0 1 2 3 4 5 6 7 8]


array([False, False, False, False, False, False,  True,  True,  True])

In [33]:
a = np.arange(9)
print(a)
flags = (a>2) & (a<=6)
flags



[0 1 2 3 4 5 6 7 8]


array([3, 4, 5, 6])

In [28]:
a = np.arange(9)
print(a)
flags = (a>2) | (a<=6)
flags


[0 1 2 3 4 5 6 7 8]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [51]:
flags2 = ~flags
flags2

array([False, False, False, False, False, False, False, False, False])